Khizanag/word-bundle

Word Bundle/Word Bundle.xcodeproj/project.pbxproj, Word Bundle/Word Bundle/Localization/Localisation Files/en.lproj/Localizable-ka.strings, Word Bundle/Word Bundle/Localization/Localisation Files/en.lproj/Localizable.strings, Word Bundle/Word Bundle/Localization/Localisation Files/ka.lproj/Localizable.strings, Word Bundle/Word Bundle/Localization/Localisation.swift, Word Bundle/Word Bundle/Models/Language.swift, Word Bundle/Word Bundle/Models/PartOfSpeech.swift, Word Bundle/Word Bundle/Models/Word.swift, Word Bundle/Word Bundle/Models/WordBundle.swift, Word Bundle/Word Bundle/Word_BundleApp.swift
https://khizanag.atlassian.net/browse/WB-11
=> WB-11: Create Languages

Word Bundle/Word Bundle.xcodeproj/project.pbxproj, Word Bundle/Word Bundle/Localization/Localisation.swift, Word Bundle/Word Bundle/Views/Reminders Setting/ReminderSettingItem.swift, Word Bundle/Word Bundle/Views/Reminders Setting/RemindersSettingView.swift
https://khizanag.atlassian.net/browse/WB-25
=> WB-25: Labels does not update for "ReminderSettingItem"

Word Bundle/Word Bundle.xcodeproj/project.pbxproj, Word Bundle/Word Bundle.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Word Bundle/Word Bundle/Models/PartOfSpeech.swift, Word Bundle/Word Bundle/Models/Word+Examples.swift, Word Bundle/Word Bundle/Models/Word.swift, Word Bundle/Word Bundle/Models/WordBundle.swift, Word Bundle/Word Bundle/Views/HomeView.swift, Word Bundle/Word Bundle/Views/LibraryView.swift, Word Bundle/Word Bundle/Views/MainView.swift, Word Bundle/Word Bundle/Views/WordView.swift, Word Bundle/Word Bundle/Word_BundleApp.swift
https://khizanag.atlassian.net/browse/WB-9
=> WB-9: Create a `Home` page

Word Bundle/Word Bundle/Views/Reminders Setting/ReminderSettingItem.swift, Word Bundle/Word Bundle/Views/Reminders Setting/RemindersSettingView.swift
https://khizanag.atlassian.net/browse/WB-28
=> WB-28: Refactor 'ReminderSettingItem'

Word Bundle/Word Bundle.xcodeproj/project.pbxproj, Word Bundle/Word Bundle.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Word Bundle/Word Bundle/Shared/SwipeModifier.swift, Word Bundle/Word Bundle/Views/Components/HelloWorldView.swift, Word Bundle/Word Bundle/Views/Components/NavigationButton.swift, Word Bundle/Word Bundle/Views/HomeView.swift, Word Bundle/Word Bundle/Views/LibraryView.swift, Word Bundle/Word Bundle/Views/MainView.swift, Word Bundle/Word Bundle/Views/Reminders Setting/ReminderSettingItem.swift, Word Bundle/Word Bundle/Views/Reminders Setting/RemindersSettingView.swift, Word Bundle/Word Bundle/Views/WelcomeView.swift, Word Bundle/Word Bundle/Views/WordView.swift, Word Bundle/Word Bundle/Word_BundleApp.swift
https://khizanag.atlassian.net/browse/WB-29
=> WB-29: Add Swipe features on Home page

Word Bundle/Word Bundle.xcodeproj/project.pbxproj, Word Bundle/Word Bundle/Models/Theme.swift, Word Bundle/Word Bundle/Models/ThemesModel.swift, Word Bundle/Word Bundle/Views/AspectVGrid.swift, Word Bundle/Word Bundle/Views/Components/ThemeView.swift, Word Bundle/Word Bundle/Views/HomeView.swift, Word Bundle/Word Bundle/Views/LibraryView.swift, Word Bundle/Word Bundle/Views/MainView.swift
https://khizanag.atlassian.net/browse/WB-1
=> WB-1: Create a `Themes Selection` page

Word Bundle/Word Bundle/Models/DTOs/RetrieveEntryResponse.swift, Word Bundle/Word Bundle/Models/Theme.swift, Word Bundle/Word Bundle/Models/ThemesModel.swift, Word Bundle/Word Bundle/Views/AspectVGrid.swift, Word Bundle/Word Bundle/Views/Components/ThemeView.swift, Word Bundle/Word Bundle/Views/LibraryView.swift, Word Bundle/Word Bundle/Views/MainView.swift, Word Bundle/Word Bundle/Views/WelcomeView.swift
https://khizanag.atlassian.net/browse/WB-14
=> WB-14: Integrate service for the Voice Pronunciation

Word Bundle/Word Bundle.xcodeproj/project.pbxproj, Word Bundle/Word Bundle/Models/DTOs/UnsplashImageResponse.swift, Word Bundle/Word Bundle/Repositories/UnsplashImageRepository.swift, Word Bundle/Word Bundle/Shared/Extensions/UIImage+Extension.swift, Word Bundle/Word Bundle/Views/WordView.swift
https://khizanag.atlassian.net/browse/WB-35
=> WB-35: Recover SplashRepository

Word Bundle/Word Bundle.xcodeproj/project.pbxproj, Word Bundle/Word Bundle/Shared/Extensions/String+Extension.swift, Word Bundle/Word Bundle/Views/MainView.swift, Word Bundle/Word Bundle/Views/WordsView.swift
https://khizanag.atlassian.net/browse/WB-34
=> WB-34: add words page

Word Bundle/Word Bundle.xcodeproj/project.pbxproj, Word Bundle/Word Bundle/Repositories/OxfordDictionariesRepository.swift, Word Bundle/Word Bundle/Repositories/UnsplashImageRepository.swift, Word Bundle/Word Bundle/Shared/Extensions/Dictionary+Extension.swift, Word Bundle/Word Bundle/Views/WelcomeView.swift
https://khizanag.atlassian.net/browse/WB-37
=> WB-37: Refactor Repositories

Word Bundle/Word Bundle/Models/DTOs/RetrieveEntryResponse.swift, Word Bundle/Word Bundle/Shared/Extensions/String+Extension.swift, Word Bundle/Word Bundle/Views/WelcomeView.swift, Word Bundle/Word Bundle/Views/WordView.swift, Word Bundle/Word Bundle/Views/WordsView.swift
https://khizanag.atlassian.net/browse/WB-36
=> WB-36: Refactor Image API Call

Word Bundle/Word Bundle.xcodeproj/project.pbxproj, Word Bundle/Word Bundle/Views/MainView.swift, Word Bundle/Word Bundle/Views/SettingsView.swift, Word Bundle/Word Bundle/Views/ThemesView.swift
https://khizanag.atlassian.net/browse/WB-41
=> Wb-41: add reminders and themes into Settings

Word Bundle/Word Bundle/Views/WordView.swift
https://khizanag.atlassian.net/browse/WB-42
=> WB-42: Refactor `Word` Page

Word Bundle/Word Bundle/Views/Components/NavigationButton.swift, Word Bundle/Word Bundle/Views/HomeView.swift, Word Bundle/Word Bundle/Views/MainView.swift, Word Bundle/Word Bundle/Views/Reminders Setting/RemindersSettingView.swift, Word Bundle/Word Bundle/Views/WelcomeView.swift
https://khizanag.atlassian.net/browse/WB-43
=> WB-43: Remove unnecessary Sections from `WelcomeView`

Word Bundle/Word Bundle/Views/MainView.swift
https://khizanag.atlassian.net/browse/WB-44
=> WB-44: Refactor Tab Bar

Word Bundle/Word Bundle/Views/WordView.swift
https://khizanag.atlassian.net/browse/WB-45
=> WB-45: Add Synonyms and Antonyms

Word Bundle/Word Bundle.xcodeproj/project.pbxproj, Word Bundle/Word Bundle/Views/CollapsibleView.swift, Word Bundle/Word Bundle/Views/WordView.swift
https://khizanag.atlassian.net/browse/WB-49
=> WB-49: Make `Synonyms` and `Antonyms` collapsible

Word Bundle/Word Bundle/Views/WordView.swift
https://khizanag.atlassian.net/browse/WB-56
=> WB-56: Remove unnecessary spacers from `Word Page`

Word Bundle/Word Bundle/Views/WordView.swift
https://khizanag.atlassian.net/browse/WB-66
=> WB-66: Add phoneticNotation to WordUI

Word Bundle/Word Bundle/Views/CollapsibleView.swift, Word Bundle/Word Bundle/Views/WordView.swift
https://khizanag.atlassian.net/browse/WB-77
=> WB-77: Fix Synonyms` Icon

Word Bundle/Word Bundle/Views/Reminders Setting/ReminderSettingItem.swift
https://khizanag.atlassian.net/browse/WB-58
=> WB-58: Refactor `Reminder Item` icons

Word Bundle/Word Bundle.xcodeproj/project.pbxproj, Word Bundle/Word Bundle/Models/TabItem.swift, Word Bundle/Word Bundle/Views/MainView.swift, Word Bundle/Word Bundle/Views/Word Bundles Views/WordBundlesView.swift
https://khizanag.atlassian.net/browse/WB-80
=> WB-80: Do navigation from `Bundles Preview Item` to `Words Page`

Word Bundle/Word Bundle/Views/Word Bundles Views/WordBundlesView.swift
https://khizanag.atlassian.net/browse/WB-78
=> WB-78: Add Delete action on long press on `Word Bundle Preview` item

Word Bundle/Word Bundle.xcodeproj/project.pbxproj, Word Bundle/Word Bundle/Entities.xcdatamodeld/Entities.xcdatamodel/contents, Word Bundle/Word Bundle/Models/AppStorageKeys.swift, Word Bundle/Word Bundle/Models/DTOs/RetrieveEntryResponse.swift, Word Bundle/Word Bundle/Models/Language.swift, Word Bundle/Word Bundle/Models/Word/WordEntity.swift, Word Bundle/Word Bundle/Models/WordBundle.swift, Word Bundle/Word Bundle/Models/WordBundle/WordBundleEntity.swift, Word Bundle/Word Bundle/Repositories/OxfordDictionariesRepository.swift, Word Bundle/Word Bundle/Shared/Extensions/UUID+Extension.swift, Word Bundle/Word Bundle/Views/HomeView.swift, Word Bundle/Word Bundle/Views/MainView.swift, Word Bundle/Word Bundle/Views/Themes View/ThemeView.swift, Word Bundle/Word Bundle/Views/Word Bundles Views/WordBundlePreviewItemView.swift, Word Bundle/Word Bundle/Views/Word Bundles Views/WordBundlesView.swift, Word Bundle/Word Bundle/Views/WordBundleView.swift, Word Bundle/Word Bundle/Views/WordView.swift
https://khizanag.atlassian.net/browse/WB-61
=> WB-61: Update `Word Entity`

Word Bundle/Word Bundle/Views/WordBundleView.swift
https://khizanag.atlassian.net/browse/WB-76
=> WB-76: Add Delete Word functional

Word Bundle/Word Bundle/Views/Languages Views/LanguagesView.swift, Word Bundle/Word Bundle/Views/WordBundleView.swift
https://khizanag.atlassian.net/browse/WB-75
=> WB-75: Add enter support for text fields

Word Bundle/Word Bundle/Views/Word Bundles Views/WordBundlePreviewItemView.swift, Word Bundle/Word Bundle/Views/Word Bundles Views/WordBundlesView.swift
https://khizanag.atlassian.net/browse/WB-81
=> WB-81: Add Stroke on Selected `Word Bundle`

Word Bundle/Word Bundle/Views/MainView.swift, Word Bundle/Word Bundle/Views/WordBundleView.swift
https://khizanag.atlassian.net/browse/WB-84
=> WB-84: Make API's language support dynamic

Word Bundle/Word Bundle/Design System/DesignSystem+Images.swift, Word Bundle/Word Bundle/Localization/Localisation Files/en.lproj/Localizable.strings, Word Bundle/Word Bundle/Localization/Localisation Files/ka.lproj/Localizable.strings, Word Bundle/Word Bundle/Localization/Localisation.swift, Word Bundle/Word Bundle/Views/CollapsibleView.swift, Word Bundle/Word Bundle/Views/Languages Views/CreateWordBundleView.swift, Word Bundle/Word Bundle/Views/Languages Views/LanguageItemView.swift, Word Bundle/Word Bundle/Views/MainView.swift, Word Bundle/Word Bundle/Views/Reminders Setting/ReminderSettingItem.swift, Word Bundle/Word Bundle/Views/Reminders Setting/RemindersSettingView.swift, Word Bundle/Word Bundle/Views/SettingsView.swift, Word Bundle/Word Bundle/Views/Themes Views/ThemeView.swift, Word Bundle/Word Bundle/Views/WelcomeView.swift, Word Bundle/Word Bundle/Views/Word Bundles Views/AddWordBundleItemView.swift, Word Bundle/Word Bundle/Views/WordBundleView.swift, Word Bundle/Word Bundle/Views/WordView.swift
https://khizanag.atlassian.net/browse/WB-89
=> WB-89: Move Images to DesignSystem

Word Bundle/Word Bundle/Repositories/OxfordDictionariesRepository.swift, Word Bundle/Word Bundle/Repositories/UnsplashImageRepository.swift, Word Bundle/Word Bundle/Views/Languages Views/CreateWordBundleView.swift, Word Bundle/Word Bundle/Views/WordBundleView.swift
https://khizanag.atlassian.net/browse/WB-99
=> WB-99: Trim TextField inputs

Word Bundle/Word Bundle.xcodeproj/project.pbxproj, Word Bundle/Word Bundle/Design System/DesignSystem+Images.swift, Word Bundle/Word Bundle/Localization/Localisation.swift, Word Bundle/Word Bundle/NetworkLayer/NetworkLayer.swift, Word Bundle/Word Bundle/Repositories/OxfordDictionariesRepository.swift, Word Bundle/Word Bundle/Repositories/UnsplashImageRepository.swift
https://khizanag.atlassian.net/browse/WB-100
=> WB-100: Create a basic Network Layer
